name: Python CI tp3Docker

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Lancer les tests
      run: PYTHONPATH=. pytest tests/

    - name: Login Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python-test-app:latest .

    - name: Push image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/python-test-app:latest